export const TOURIST_PREFERENCES = [
  { label: "Adventure", value: "adventure" },
  { label: "Culture", value: "culture" },
  { label: "Beach", value: "beach" },
  { label: "Nature", value: "nature" },
  { label: "City", value: "city" },
  { label: "Food", value: "food" },
  { label: "Nightlife", value: "nightlife" },
];

export const GUIDE_EXPERTISE = [
  { label: "Adventure", value: "adventure" },
  { label: "Culture", value: "culture" },
  { label: "Beach", value: "beach" },
  { label: "Nature", value: "nature" },
  { label: "City", value: "city" },
  { label: "Food", value: "food" },
  { label: "Nightlife", value: "nightlife" },
];

export const WEEK_DAYS = [
  { label: "Monday", value: "monday" },
  { label: "Tuesday", value: "tuesday" },
  { label: "Wednesday", value: "wednesday" },
  { label: "Thursday", value: "thursday" },
  { label: "Friday", value: "friday" },
  { label: "Saturday", value: "saturday" },
  { label: "Sunday", value: "sunday" },
];

export const ADMIN_PERMISSIONS = [
  { label: "Manage Users", value: "manage_users" },
  { label: "Manage Guides", value: "manage_guides" },
  { label: "Manage Tours", value: "manage_tours" },
  { label: "Manage Bookings", value: "manage_bookings" },
  { label: "Manage Reviews", value: "manage_reviews" },
  { label: "Manage Payments", value: "manage_payments" },
  { label: "View Reports", value: "view_reports" },
  { label: "System Settings", value: "system_settings" },
];

export const TOUR_CATEGORIES = [
  { label: "Adventure", value: "adventure" },
  { label: "Culture", value: "culture" },
  { label: "Beach", value: "beach" },
  { label: "Nature", value: "nature" },
  { label: "City", value: "city" },
  { label: "Food", value: "food" },
  { label: "Nightlife", value: "nightlife" },
];

export const TOUR_DURATIONS = [
  { label: "3 Hours", value: 180 },
  { label: "4 Hours", value: 240 },
  { label: "5 Hours", value: 300 },
  { label: "6 Hours", value: 360 },
  { label: "8 Hours", value: 480 },
  { label: "12 Hours", value: 720 },
  { label: "1 Day", value: 1440 },
  { label: "2 Days", value: 2880 },
  { label: "3 Days", value: 4320 },
  { label: "5 Days", value: 7200 },
  { label: "7 Days", value: 10080 },
];

export const GROUP_SIZES = [
  { label: "1–2 People", value: 2 },
  { label: "3–5 People", value: 5 },
  { label: "6–8 People", value: 8 },
  { label: "9–12 People", value: 12 },
  { label: "Large Group (15+)", value: 15 },
];

export const GUIDE_SPECIALTIES = [
  "Adventure Tours",
  "National Parks",
  "Hiking",
  "Mountain Trekking",
  "Wildlife Spotting",
  "Survival Skills",
  "Heritage Tours",
  "Museums",
  "Royal History",
  "Great Barrier Reef",
  "Outback Safaris",
  "Marine Biology",
  "Ancient Ruins",
  "Vatican Tours",
  "Culinary Walks",
  "Tapas Tours",
  "Gaudí Architecture",
  "Local History",
  "Carnival Tours",
  "Beach Excursions",
  "Samba Classes",
  "Louvre Tours",
  "Historical Landmarks",
  "Wine Tasting",
  "Walking Tours",
  "Street Food",
  "Aztec History",
  "Temple Tours",
  "Tea Ceremonies",
  "Zen Gardens",
  "Island Hopping",
  "Nightlife",
  "Scuba Diving",
  "Volcano Trekking",
  "Surf Lessons",
  "Temple Visits",
  "Safaris",
  "Table Mountain Treks",
  "Wine Routes",
  "Bazaar Navigation",
  "Ottoman History",
  "Culinary Tours",
  "Desert Safaris",
  "Luxury Tours",
  "Modern Architecture",
  "Sunset Sailing",
  "Archaeology",
  "Fado Music",
  "Historical Walks",
  "Gastronomy",
  "WWII History",
  "Street Art",
  "Museum Island",
  "Canal Cruises",
  "Cycling Tours",
  "Art History",
  "Hawker Centers",
  "Heritage Districts",
  "Botanic Gardens",
];
