import { UserRole } from "../generated/enums";

export const guides = [
  {
    name: "Mia Thompson",
    email: "guide21@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000022",
    country: "New Zealand",
    bio: "Eco-tourism and hiking guide.",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    city: "Queenstown",
    languages: ["English", "Maori"],
    specialties: ["Eco-tourism", "Hiking", "Flora and Fauna"],
    aboutMe:
      "I grew up exploring the majestic fjords and mountains of New Zealand. My passion is sharing the hidden gems of our beautiful landscape while promoting sustainable and responsible travel.",
  },
  {
    name: "Harper White",
    email: "guide22@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000023",
    country: "Ireland",
    bio: "Folklore and countryside tours.",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    city: "Galway",
    languages: ["English", "Irish (Gaelic)"],
    specialties: ["Folklore", "Countryside Walks", "Historical Tours"],
    aboutMe:
      "With a deep love for Irish myths and legends, I guide visitors through the breathtaking landscapes of the Emerald Isle, sharing stories that have been passed down for generations.",
  },
  {
    name: "Evelyn Clark",
    email: "guide23@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000024",
    country: "Switzerland",
    bio: "Alpine skiing and snowboarding guide.",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    city: "Zermatt",
    languages: ["English", "German", "French"],
    specialties: ["Skiing", "Snowboarding", "Alpine Safety"],
    aboutMe:
      "As a certified ski instructor and alpine enthusiast, I spend my winters on the slopes of the Matterhorn. I cater to all skill levels, ensuring a safe and thrilling mountain experience.",
  },
  {
    name: "Abigail Lewis",
    email: "guide24@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000025",
    country: "Peru",
    bio: "Inca trail and historical ruins expert.",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    city: "Cusco",
    languages: ["English", "Spanish", "Quechua"],
    specialties: ["Inca Trail", "Archaeology", "High Altitude Trekking"],
    aboutMe:
      "I've hiked the Inca Trail over fifty times and still find myself in awe of Machu Picchu. I love weaving the rich history of the Inca empire into our physical journey through the Andes.",
  },
  {
    name: "Emily Robinson",
    email: "guide25@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000026",
    country: "Egypt",
    bio: "Ancient pyramids and Nile cruise guide.",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    city: "Cairo",
    languages: ["English", "Arabic"],
    specialties: ["Egyptology", "River Cruises", "Desert Excursions"],
    aboutMe:
      "Holding a degree in Egyptology, I bring ancient history to life. From the bustling streets of Cairo to the tranquil waters of the Nile, I ensure my guests get a truly immersive historical experience.",
  },
  {
    name: "Elizabeth Walker",
    email: "guide26@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000027",
    country: "Morocco",
    bio: "Desert camping and souk tours.",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    city: "Marrakech",
    languages: ["English", "Arabic", "French"],
    specialties: ["Desert Camping", "Market Navigation", "Moroccan Cuisine"],
    aboutMe:
      "I specialize in creating unforgettable experiences in the Sahara and navigating the vibrant chaos of the medinas. Join me for an authentic taste of Moroccan hospitality and culture.",
  },
  {
    name: "Sofia Hall",
    email: "guide27@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000028",
    country: "Argentina",
    bio: "Wine tasting and Patagonia trekking.",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    city: "Mendoza",
    languages: ["English", "Spanish"],
    specialties: ["Wine Tasting", "Glacier Treks", "Cultural Tours"],
    aboutMe:
      "Whether we are sipping Malbec in the vineyards of Mendoza or strapping on crampons to explore the Perito Moreno Glacier, I am dedicated to showcasing the diverse beauty of Argentina.",
  },
  {
    name: "Avery Young",
    email: "guide28@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000029",
    country: "Vietnam",
    bio: "Motorbike tours and street food expert.",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    city: "Hanoi",
    languages: ["English", "Vietnamese"],
    specialties: ["Motorbike Tours", "Street Food", "Urban Exploration"],
    aboutMe:
      "The best way to see Vietnam is on two wheels and with an empty stomach! I love taking travelers off the beaten path to discover secret food stalls and stunning rural landscapes.",
  },
  {
    name: "Ella Allen",
    email: "guide29@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000030",
    country: "Iceland",
    bio: "Northern lights and glacier explorer.",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    city: "Reykjavik",
    languages: ["English", "Icelandic"],
    specialties: ["Northern Lights", "Glacier Hiking", "Geology"],
    aboutMe:
      "Iceland is a land of fire and ice, and I am fascinated by its unique geology. I'm an expert at chasing the Aurora Borealis and safely guiding groups across our majestic glaciers.",
  },
  {
    name: "Scarlett King",
    email: "guide30@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000031",
    country: "Kenya",
    bio: "Big Five safari specialist.",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    city: "Nairobi",
    languages: ["English", "Swahili"],
    specialties: ["Wildlife Photography", "Safari Planning", "Conservation"],
    aboutMe:
      "Born near the Maasai Mara, wildlife conservation is in my blood. I guide thrilling safaris with a strong emphasis on respecting the animals and supporting local indigenous communities.",
  },
  {
    name: "Grace Wright",
    email: "guide31@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000032",
    country: "India",
    bio: "Spiritual retreats and heritage walks.",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    city: "Varanasi",
    languages: ["English", "Hindi"],
    specialties: ["Spiritual Retreats", "Heritage Walks", "Yoga"],
    aboutMe:
      "I offer a journey into the soul of India. Whether navigating the ancient ghats of Varanasi or exploring centuries-old temples, I help travelers find peace and profound cultural connection.",
  },
  {
    name: "Chloe Lopez",
    email: "guide32@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000033",
    country: "Colombia",
    bio: "Coffee region and salsa dancing tours.",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    city: "Medellín",
    languages: ["English", "Spanish"],
    specialties: ["Coffee Tours", "Salsa Dancing", "Urban History"],
    aboutMe:
      "I am passionate about Colombia's vibrant transformation. I will take you from the lush green hills of our coffee farms to the lively dance floors of Medellín, sharing the rhythm of my country.",
  },
  {
    name: "Victoria Hill",
    email: "guide33@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000034",
    country: "Costa Rica",
    bio: "Rainforest canopy and wildlife guide.",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
    city: "San José",
    languages: ["English", "Spanish"],
    specialties: ["Canopy Tours", "Bird Watching", "Eco-Tourism"],
    aboutMe:
      "Pura Vida! I am an avid naturalist who loves showing visitors the incredible biodiversity of our rainforests. From sloth spotting to thrilling ziplines, I make every tour an adventure.",
  },
  {
    name: "Riley Scott",
    email: "guide34@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000035",
    country: "Croatia",
    bio: "Sailing and coastal town expert.",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    city: "Split",
    languages: ["English", "Croatian"],
    specialties: ["Sailing", "Island Hopping", "Medieval History"],
    aboutMe:
      "Growing up on the Dalmatian coast, the Adriatic Sea is my second home. I specialize in customized sailing trips and exploring the rich medieval history of our beautiful island towns.",
  },
  {
    name: "Aria Green",
    email: "guide35@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000036",
    country: "South Korea",
    bio: "K-pop culture and traditional palace tours.",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    city: "Seoul",
    languages: ["English", "Korean"],
    specialties: ["K-pop Culture", "Historical Palaces", "Korean BBQ"],
    aboutMe:
      "I bridge the gap between traditional and modern Korea. We can explore the serene grounds of Gyeongbokgung Palace in the morning and dive into the vibrant K-pop scene by night.",
  },
  {
    name: "Lily Adams",
    email: "guide36@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000037",
    country: "Chile",
    bio: "Atacama desert and stargazing guide.",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    city: "San Pedro de Atacama",
    languages: ["English", "Spanish"],
    specialties: ["Stargazing", "Desert Treks", "Astrophotography"],
    aboutMe:
      "The Atacama Desert has the clearest skies on Earth. As an amateur astronomer, I love combining rugged desert exploration during the day with breathtaking stargazing tours at night.",
  },
  {
    name: "Aubrey Nelson",
    email: "guide37@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000038",
    country: "Jordan",
    bio: "Petra and Wadi Rum adventure guide.",
    avatar: "https://randomuser.me/api/portraits/women/17.jpg",
    city: "Amman",
    languages: ["English", "Arabic"],
    specialties: ["Petra Exploration", "Desert Safaris", "Bedouin Culture"],
    aboutMe:
      "I am deeply connected to the history of the Nabataeans. Walking through the Siq to reveal the Treasury at Petra never gets old, and I love sharing authentic Bedouin tea experiences in Wadi Rum.",
  },
  {
    name: "Zoey Mitchell",
    email: "guide38@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000039",
    country: "Philippines",
    bio: "Scuba diving and island hopping expert.",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    city: "Cebu",
    languages: ["English", "Tagalog", "Cebuano"],
    specialties: ["Scuba Diving", "Island Hopping", "Marine Biology"],
    aboutMe:
      "With over 7,000 islands, the Philippines is a diver's paradise. I am a certified Divemaster dedicated to showing you our vibrant coral reefs while advocating for marine conservation.",
  },
  {
    name: "Penelope Perez",
    email: "guide39@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000040",
    country: "Malta",
    bio: "Medieval history and Mediterranean cruises.",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    city: "Valletta",
    languages: ["English", "Maltese", "Italian"],
    specialties: [
      "Medieval Architecture",
      "Mediterranean Cruises",
      "Knights of St. John",
    ],
    aboutMe:
      "Malta is an open-air museum. I guide visitors through the fortified city of Valletta and crystal-clear waters, bringing the dramatic history of the Knights of St. John to life.",
  },
  {
    name: "Lillian Roberts",
    email: "guide40@tourbuddy.com",
    password: "guide123@#",
    role: UserRole.GUIDE,
    phone: "+10000000041",
    country: "Austria",
    bio: "Classical music and architecture tours.",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    city: "Vienna",
    languages: ["English", "German"],
    specialties: ["Classical Music", "Baroque Architecture", "Cafe Culture"],
    aboutMe:
      "Vienna is the capital of classical music. I combine tours of majestic Habsburg palaces with exclusive insights into our world-famous musical heritage and traditional coffeehouse culture.",
  },
];
