import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Field, FieldContent, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { ChevronLeftIcon } from "lucide-react";
import Image from "next/image";
import React from "react";
import { toast } from "sonner";

type Props = {
  open: boolean;
  setOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setRootOpen: React.Dispatch<React.SetStateAction<boolean>>;
  dataUrl: string;
  secret: string;
};

const AuthenticatorSetup = ({
  open,
  setOpen,
  setRootOpen,
  dataUrl,
  secret,
}: Props) => {
  const [otpOpen, setOtpOpen] = React.useState(false);
  return (
    <div>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <Button
              variant="outline"
              size="icon"
              onClick={() => {
                setOpen(false);
                setRootOpen(true);
              }}
            >
              <ChevronLeftIcon />
            </Button>
            <DialogTitle> Instructions for setup</DialogTitle>
            <DialogDescription className="text-start">
              1. Install an authenticator app on your mobile device, such as
              Google Authenticator or Authy.
            </DialogDescription>
            <DialogDescription className="text-start">
              2. Open the app and scan the QR code below. If you can&apos;t scan
              the QR code, you can manually enter the secret key:{" "}
              <span className="font-mono">{secret}</span>
            </DialogDescription>
            <Image
              src={dataUrl}
              width={144}
              height={144}
              alt="QR Code"
              className="my-1 w-36 h-36"
            />
            <div className="w-full flex flex-col items-start text-start">
              <code
                color="blue"
                className=" line-clamp-2 wrap-break-word whitespace-pre-wrap break-after-right break-all break-before-right bg-muted/50 p-2 rounded-md w-full text-center font-mono "
              >
                {secret}
              </code>
              <div
                className="text-sm py-2 mt-1 text-primary cursor-pointer"
                onClick={() => {
                  navigator.clipboard.writeText(secret);
                  toast.success("copied to clipboard");
                }}
              >
                Copy Key
              </div>
            </div>
            <DialogDescription className="text-start">
              3. The app will generate a 6-digit code. Enter that code in the
              field below to verify and complete the setup.
            </DialogDescription>
          </DialogHeader>
          <Button
            onClick={() => {
              setOpen(false);
              setOtpOpen(true);
            }}
            className="mt-4"
          >
            Enter Code
          </Button>
        </DialogContent>
      </Dialog>
      <EnterOtp
        otpOpen={otpOpen}
        setOtpOpen={setOtpOpen}
        setRootOpen={setOpen}
      />
    </div>
  );
};

const EnterOtp = ({
  otpOpen,
  setOtpOpen,
  setRootOpen,
}: {
  otpOpen: boolean;
  setOtpOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setRootOpen: React.Dispatch<React.SetStateAction<boolean>>;
}) => {
  return (
    <div>
      <Dialog open={otpOpen} onOpenChange={setOtpOpen}>
        <DialogContent>
          <DialogHeader>
            <Button
              variant="outline"
              size="icon"
              onClick={() => {
                setOtpOpen(false);
                setRootOpen(true);
              }}
            >
              <ChevronLeftIcon />
            </Button>
            <DialogTitle>
              Get your code from your authentication app
            </DialogTitle>
            <DialogDescription className="text-start">
              Enter the 6-digit code generated by your authentication app.
            </DialogDescription>
          </DialogHeader>
          {/* Add OTP input field here */}
          <Field>
            <FieldLabel htmlFor="otp" className="w-full">
              Verification Code
            </FieldLabel>
            <FieldContent>
              <Input id="otp" />
            </FieldContent>
          </Field>
          <Button>Verify</Button>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default AuthenticatorSetup;
